name: publish-my-model

on:
  push:
    branches:
        - cd-main
    paths:
        - svm-app.mlem.state

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download model
        run: dvc pull -r read-write

      - name: Deploy model
        run: |
          mlem deployment run flyio svm-app \
          --model model/svm \
          --app_name svm-mlem